# Generated by Django 3.0.4 on 2020-05-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduateapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='special',
            new_name='特殊生',
        ),
    ]
