# Generated by Django 3.0.4 on 2020-05-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduateapp', '0005_auto_20200518_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(max_length=8)),
                ('class_name', models.CharField(max_length=20)),
                ('credit', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=10)),
                ('year_in_school', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=10)),
                ('time', models.CharField(max_length=100)),
                ('classify1', models.CharField(choices=[('必修', '必修'), ('選修', '選修')], default='必修', max_length=10)),
                ('classify2', models.CharField(choices=[('系上', '系上'), ('通識', '通識')], default='系上', max_length=10)),
                ('english', models.BooleanField(default='False')),
                ('must', models.BooleanField(default='False')),
            ],
        ),
    ]
