# Generated by Django 3.0.4 on 2020-05-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduateapp', '0006_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='special',
            new_name='HK',
        ),
        migrations.RemoveField(
            model_name='course',
            name='must',
        ),
        migrations.AddField(
            model_name='course',
            name='compolsory',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='student',
            name='dep_transfer',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='student',
            name='early',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='student',
            name='exchange',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='student',
            name='postpone',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='student',
            name='preparation',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='student',
            name='repeat',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='student',
            name='sch_transfer',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='course',
            name='english',
            field=models.BooleanField(default='True'),
        ),
    ]
